title: Seasoned Chaos
description: > # this means to ignore newlines until "baseurl:"
  Subseasonal to seasonal forecasting blog for scientists & non-scientists alike
permalink: ':title/'
#baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "http://seasonedchaos.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "https://twitter.com/seasonedchaos"

# Author Settings
author: Seasoned Chaos # add your name
author-img: SC_logo.jpg # add your photo
about-author: Subseasonal to seasonal forecasting blog for scientists & non-scientists alike # add description
social-twitter: "seasonedchaos"
#social-facebook: # add your Facebook handle
#social-github: artemsheludko # add your Github handle
#social-linkedin: # add your Linkedin handle
social-email: seasonedchaos@gmail.com # add your Email address

# Disqus
discus-identifier: seasoned-chaos # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
